### ISSUE TITLE
Animation starts before calling getTargetCurrent

### ISSUE THREAD

**Issue by EskAere** [RafaelBarbosatec/tutorial_coach_mark#51] opened 2021-02-16 13:04 UTC
Hi :) 

First, thank you for this package. It's really helpful. 

I'm wondering why but let's say I start a tutorial with a target in the center of the screen, I'll always have few frames where the targetPosition seems to be at the top ? So the animation starts towards this top position, then snaps to the center. 

In the end, my target is correctly focused, but it's visually unpleasant. 

I noticed that the animation is starting even before getTargetCurrent is called.

**Comment by RafaelBarbosatec** [comment] 2021-06-08 20:01
Hi @EskAere !
Thanks for this comment.
Does this still happen?
I couldn't reproduce it.

**Comment by RafaelBarbosatec** [comment] 2021-06-14 16:32
Resolved in  1.0.3 version

**Closed by RafaelBarbosatec** 2021-06-14 16:32 UTC
